### PR TITLE
feat: Add load-testing repo

### PR DESCRIPTION
**Pull request by viccuad**
## Description

feat: Add load-testing repo.

### CODE REVIEW

**Review by jvanz — COMMENTED** [review]
The file seems fine to me. I have only one question. Have you follow the docs about importing the repo? I'm asking that because if we add the repo without importing it, we can mess up with the repos. Because the state of the modules will not match the reality.

**Comment by viccuad** [comment]
Indeed, I didn't!

I have now installed a matchin terraform version, and do the `terraform init; terraform import; terraform plan`. The `terraform plan` looks fine here, it makes the needed changes to the load-testing repo.

Needed to revert the bump of the terraform github module done in the past, as terraform fails to download that module version.

**Review by jvanz — APPROVED** [review]
LGTM! :D

**Review by jvanz — APPROVED** [review]

**Comment by viccuad** [comment]
merged https://github.com/kubewarden/automation/pull/21, which bumps the github provider, so my revert is not needed. Hence, I have rebased main and dropped my revert.

**Comment by jvanz** [comment]
> merged #21, which bumps the github provider, so my revert is not needed. Hence, I have rebased main and dropped my revert.

Cool, it seems good to me. After merging this PR, we need to apply the changes and update the state again and update the file once more.

**Comment by flavio** [comment]
I've applied the changes via `terraform apply`

**Pull request merged**
